_BASE_: "Base-RCNN-FPN.yaml"
SEED: 16
MODEL:
  WEIGHTS: "https://s3.unistra.fr/camma_public/github/adaptor/models/R-50_moco_v2.pkl"
  MASK_ON: True
  KEYPOINT_ON: True
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]  
  BACKBONE:
    FREEZE_AT: 0  
  RESNETS:
   DEPTH: 50
   NORM: "GN"
   STRIDE_IN_1X1: False
  FPN:
    NORM: "GN"       
  ROI_HEADS:
    NAME: "CustomROIHeads"
    NUM_CLASSES: 1  
  ROI_BOX_HEAD:
   LOSS: "FocalLoss"
   NUM_CONV: 4
   NUM_FC: 1
   NORM: "GN"
   SMOOTH_L1_BETA: 0.5
  ROI_KEYPOINT_HEAD:
   NAME: "KRCNNConvDeconvUpsampleHeadGN"
   NORM: "GN"
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHeadGN"
    NORM: "GN"
  RPN:
    POST_NMS_TOPK_TRAIN: 1500
SOLVER:
  IMS_PER_BATCH_LBL: 8
  IMS_PER_BATCH_UNLBL: 8
  BASE_LR: 0.01
  STEPS: (359980, 359990)
  MAX_ITER: 360000  
  USE_EMA: True
  EMA_DECAY: 0.9996
  CHECKPOINT_PERIOD: 10000
  AMP:
    ENABLED: True
  
DATASETS:
  TRAIN: ("keypoints_coco_2017_train",)
  TEST: ("keypoints_coco_2017_val",)

DATALOADER:
  RANDOM_DATA_SEED: 1

UDA:
  ENABLE: False
  TYPE: "ssl_coco"
  BBOX_THRESHOLD: 0.7
  MASK_THRESHOLD: 0.5
  KEYPOINT_THRESHOLD: 0.1
  LAMBDA_U: 2.0
  LAMBDA_U_KEYPOINT: 2.0
  LAMBDA_U_MASK: 2.0
  APPLY_RAND_AUGMENT: True
  APPLY_LOW_RES_RESIZE: False
  APPLY_GEOMETRIC_TRANSFORM: True
  ADD_STRONGAUG_EXAMPLES: True
  TRAIN_SUP_ITER: 10000
  RANDOM_AUGMENT_THRESH1: 0.95
  RANDOM_AUGMENT_THRESH2: 0.05

INPUT:
  FORMAT: "RGB"

TEST:
  EVAL_PERIOD: 5000